jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    adm: { password: %security_password%, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: _security_check
                login_path: _admin_login
                username_parameter: 'form[username]'
                password_parameter: 'form[password]'
            logout:
                path:   _admin_logout
                target: _icup

        secured_area:
            pattern:    ^/
            anonymous: ~
            switch_user: true
            form_login:
                check_path: _security_check
                login_path: _admin_login
                username_parameter: 'form[username]'
                password_parameter: 'form[password]'
            logout:
                path:   _admin_logout
                target: _icup

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
