form:
    template: pfa
    company: The Training Company
    signer: Henrik Vrangbæk Thomsen
    email: info@training-comp.dk
    invitation:
        title: The Training Company har brug for din mening
        body: >
            Kære %receiver%<br />
            <br />
            I forbindelse med det kommende kursusforløb har vi behov for dit input via et spørgeskema.<br />
            <br />
            Din besvarelse af spørgeskemaet tager ca. 5 min. og gennemføres via nedenstående link.<br />
            <br />
            <a href="%link%" target="_blank">Klik her for at starte undersøgelsen</a><br/>
            <br />
            Besvarelsen bedes gennemført senest den 30. januar.<br />
            <br />
            På forhånd tak for din besvarelse.<br />
            <br />
            Med venlig hilsen<br/>
            %sender%<br/>
            The Training Company<br/>
            <br/>
    pages:
        gruppe:
            title: Gruppeadfærd
            description: >
                Angiv den grad af enighed du deler med følgende udsagn om din gruppeadfærd
            blocks:
                f1: 
                    type: satisfaction
                    valuelist:
                        1: Meget uenig
                        2: Mindre uenig
                        3: Lidt uenig
                        4: Enig
                        5: Lidt enig
                        6: Mere enig
                        7: Meget enig
                    labels:
                        # Løsningsorienteret
                        - Jeg skaber hurtigt kontakt med andre mennesker
                        - Jeg kan lide at stå op og tale i en forsamling
                        # Proaktiv
                        - Jeg tager naturligt styringen i en gruppe
                        - Jeg påtaler gerne mangler i andres arbejde
                        # Reaktiv
                        - Jeg bruger tid på at detaljer er korrekte
                        - Jeg bruger tid på at det jeg afleverer er korrekt
                        # Problemorienteret
                        - Jeg kan godt lide faste rammer for mit arbejde
                        - Jeg synes forandringer i hverdagen er en udfordring
        kultur:
            title: Kultur
            description: >
                Angiv den grad af enighed du deler med følgende udsagn om kultur
            blocks:
                f1: 
                    type: satisfaction
                    valuelist:
                        1: Meget uenig
                        2: Mindre uenig
                        3: Lidt uenig
                        4: Enig
                        5: Lidt enig
                        6: Mere enig
                        7: Meget enig
                    labels:
                        # Projektorienteret
                        - Vi er meget innovative i vores firma
                        - Vi udvikler kreative løsninger på problemer i firmaet
                        # Analyserende
                        - Vi undersøger tingene til bunds i firmaet
                        - Vi er grundige i analyser før beslutning i vores firma
                        # Defensiv
                        - Vi har høj fokus på omkostninger i firmaet
                        - Vi investerer lidt i nyudviklingen i firmaet
                        # Reaktiv
                        - Vi følger branchens priser, ydelser og serviceniveau i vores firma
                        - Vi inspireres af andre firmaer i branchen
        adfærd:
            title: Adfærd
            description: >
                Angiv den grad af enighed du deler med følgende udsagn om din adfærd
            blocks:
                f1: 
                    type: satisfaction
                    valuelist:
                        1: Meget uenig
                        2: Mindre uenig
                        3: Lidt uenig
                        4: Enig
                        5: Lidt enig
                        6: Mere enig
                        7: Meget enig
                    labels:
                        # Løsningsorienteret
                        - Jeg tager gerne beslutninger og ansvar på mig
                        - Jeg tager initiativ til at løse problemer på forhånd
                        # Proaktiv
                        - Jeg finder tit nye løsninger til et problem
                        - Jeg ser ofte flere muligheder for løsning af et problem
                        # Reaktiv
                        - Jeg afventer en fælles beslutning på et problem
                        - Jeg holder mig til reglerne når jeg løser et problem
                        # Problemorienteret
                        - Jeg finder tit svære udfordringer i mit job
                        - Jeg synes rammerne for mit arbejde gør det svært at udføre jobbet
